### ISSUE TITLE
Finnish Osuuspankki support

### ISSUE THREAD

**Issue by kakoni** [devlab-oy/sepa#30]
First, seriously cool project, awesome work.

Question;
Is Finnish OP-Pohjola using this same xml-api as nordea/danske?
So adding OP-support should be pretty straight forwarded?

**Comment by jonikanerva** [comment]
Thanks for the kind words! :)

This is a SEPA standard, so all banks in EU (and in the other 6 SEPA countries) *should* be using the same format. Unfortunately, in practice, this is not the case. That is why we decided to enable banks one at a time in the codebase (once we've been able to test them).

We never got around to requesting the developer account from OP-Pohjola, so we haven't tested their implementation yet. It is the next bank we would like to implement, but we haven't made any plans to start that work at the moment.

If you are an OP customer and have their developer account, we sure could use the help. :)
