### ISSUE TITLE
Does this really support Danske?

### ISSUE THREAD

**Issue by tjnurmin** [devlab-oy/sepa#44]
In `README` it says basic operations require `Your encryption certificate (Danske Only)` but if I try to add that to my command, I get

`undefined method own_encryption_certificate`

So it seems your README is not correct or what's going on here?

**Comment by tiere** [comment]
Your encryption certificate is not actually needed as a parameter for the standard operations but is merely sent to the bank initially when creating the certificates in the form of a certificate signing request. This way the bank can encrypt the messages with your certificate and only you can decrypt them with your encryption private key.

The process of creating the certificates and sending them to the bank for signing is explained in https://github.com/devlab-oy/sepa#downloading-danske-bank-certificates.

The gem is currently used in production with Danske and is working properly in answer to your initial question.

**Comment by tjnurmin** [comment]
OK, thanks, in that case `README` might need some clarification. I can do that at some point.

**Comment by baohle** [comment]
@tjnurmin were you able to get the gem to work for Danske Bank?

I'm receiving this: pkif:ReturnTextHard backend error. May be a problem with the PKCS#10 requests. Not sure what the problem is, and their integration team can't help me without seeing the unencrypted contents. What steps did you take?

I created the csr and keys as explained in the README, but I might be doing something wrong. These are the steps I took.

    file1 = File.open("signing.csr", "rb")
    signing_csr_contents = file1.read

    file2 = File.open("signing.key", "rb")
    signing_key_contents = file2.read

    file3 = File.open("encryption.csr", "rb")
    encryption_csr_contents = file3.read

    file4 = File.open("encryption.key", "rb")
    encryption_key_contents = file4.read

    get_bank_certificate_params = {
      bank: :danske,
      command: :get_bank_certificate,
      customer_id: '6H8805',
      environment: 'production',
      pin: '####'
    }
    sepa_client = Sepa::Client.new get_bank_certificate_params
    response = sepa_client.send_request
    bank_encryption_certificate = response.bank_encryption_certificate

    create_certificate_params = {
      bank: :danske,
      bank_encryption_certificate: "#{bank_encryption_certificate}",
      command: :create_certificate,
      customer_id: '######',
      environment: 'production',
      encryption_csr: "#{encryption_csr_contents}",
      signing_csr: "#{signing_csr_contents}",
      pin: '####'
    }

    sepa_client = Sepa::Client.new create_certificate_params
    response = sepa_client.send_request
    own_signing_certificate = response.own_signing_certificate

Not sure if you have any additional insight to what's going on.

**Comment by tjnurmin** [comment]
@baohle - no, I could not make this work. I closed the issue too early and did not have time to work on this later. So, IMO, Danske part is not working or documentation is flawed.

**Comment by baohle** [comment]
I was able to create a certificate against the test environment, and it seems that I was able to get a response from the bank's web service:

<ResponseCode>02</ResponseCode>
<ResponseText>SOAP signature error - Signature verification failed.</ResponseText>

Perhaps I'm unable to push/pull files while in test mode.

I'm in contact with the bank to see if it's an issue on my end or theirs.

**Comment by tjnurmin** [comment]
Did you manage to fetch certificate from Danske? I could not.

**Comment by baohle** [comment]
@tjnurmin only in test mode. This is what my code looked like. 

    get_bank_certificate_params = {
      bank: :danske,
      command: :get_bank_certificate,
      customer_id: '360817',
      environment: 'test',
      pin: '1234'
    }
    sepa_client = Sepa::Client.new get_bank_certificate_params
    response = sepa_client.send_request
    bank_encryption_certificate = response.bank_encryption_certificate

    create_certificate_params = {
      bank: :danske,
      bank_encryption_certificate: "#{bank_encryption_certificate}",
      command: :create_certificate,
      customer_id: '360817',
      environment: 'test',
      encryption_csr: "#{encryption_csr_contents}",
      signing_csr: "#{signing_csr_contents}",
      pin: '1234'
    }

    sepa_client = Sepa::Client.new create_certificate_params
    response = sepa_client.send_request
    own_signing_certificate = response.own_signing_certificate
    own_encryption_certificate = response.own_encryption_certificate
    ca_certificate = response.ca_certificate

    puts response

Seemed to have returned a valid response.

**Comment by tjnurmin** [comment]
@baohle - roger that. Your instructions helped immensely and I too could run this successfully in test environment. I don't have production id's for Danske currently but when I do, I will carry on with testing.

**Comment by mnskiran** [comment]
@baohle - In the production mode, did you overcome  "Hard backend error. May be a problem with the PKCS#10 requests". Me too stuck at the same error. Please help.

**Comment by tjnurmin** [comment]
I have now production id's from Danske and I could fetch certificates successfully in production.

@mnskiran - in what operation did you get that error? What were you trying to do?

**Comment by mnskiran** [comment]
@tjnurmin 
Hi Tapio, Thanks for replying on this. I could solve this issue both in Test and Production environments. The issue was with encoding the pkcs#10 request into bytes which will be converted into a base64encoded string later. I am using bountycastle library and should use pkcs10RequestObj.GetEncoded() instead of using .Net framework's Encoding class.

Hope this helps someone following same approach as mine.

**Comment by tjnurmin** [comment]
I incorporated instructions laid out in

https://github.com/devlab-oy/sepa/issues/44#issuecomment-292606172

to

https://github.com/devlab-oy/sepa/pull/72

IMO that will improve `readme` section for Danske considerably. It was only with @baohle 's tips that I managed to get this to work with Danske.
