### ISSUE TITLE
Throwing GemRequireError during rails server

### ISSUE THREAD

**Issue by baseless** [devlab-oy/sepa#51]
Hi!
I have an issue trying to run sepafm in a rails project, running on windows. When executing `rails server`  it will throw throw following exception:

```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'sepafm'. (Bundler::GemRequireError)
Gem Load Error is: not enough data
Backtrace for gem load error is:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sepafm-1.1.7/lib/sepafm.rb:62:in `initialize'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sepafm-1.1.7/lib/sepafm.rb:62:in `new'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sepafm-1.1.7/lib/sepafm.rb:62:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
```

The same project works perfectly fine under linux, and this is the only gem in the project that causes this so my first question is if this requires anything not available under windows? Or something that can be configured?

The current (tested some different configurations) environment is:

> Windows 10 / Server 2012 R2
> ruby 2.2.5p319 (2016-04-26 revision 54774) [x64-mingw32]
> Rails 4.2.6
> gem 2.4.5.1
> sepafm 1.1.7 (though the same issue occurs in the older versions as well).

**Comment by Xtreeem** [comment]
Hi. 

I am getting the same error when trying to run my webservice. 
The service is hosted on an IIS windows server.
I have tried running it with both Helicon and HttpPlatformManager, both with the same result. 

Watching this issue with great interest. 
Best regards.

**Comment by tiere** [comment]
Hi,

I'll try the gem on a Windows machine later today and try to reproduce the problem and figure out what could be causing it.

**Comment by baseless** [comment]
To fill in my earlier post, what was done here to reproduce the error:
1. Just install ruby 2.2.5 from rubyinstaller followed by the latest devkit (x64).
2. Run 'ruby dk.rb init' and 'ruby dk.rb install' for the devkit.
3. 'gem install rails --version 4.2.6'
4. 'rails _4.2.6_ new sepaproj'
5. Add 'gem 'sepafm', '1.1.7'' to the Gemfile (or without version notation)
6. 'bundle install'
7. run 'rails server'

Got the same issue when using railsinstaller (ruby 2.2.4, rails 4.2.5, sepafm 1.1.5).

**Comment by tiere** [comment]
Hi,

I've figured out where the problem lies. On Windows, files need to be explicitly read as binary and that's why some certificates cannot currently be initialized correctly since they are saved as binary on the disk. I'll update this thread when I have fixed the issue.

**Comment by Xtreeem** [comment]
Hello. 

Thanks for the quick feedback, it is very much appreciated.

**Comment by baseless** [comment]
Would it be possible to get your thought in regards to the timeframe for the fix? So i have an idea what i can expect :).

**Comment by tiere** [comment]
Hi,

I'll try to get the fix written today.

**Comment by tiere** [comment]
Fix: #52

**Comment by baseless** [comment]
Tested this by replacing `gem 'sepafm', '1.1.7'` with `gem 'sepafm', :git => 'https://github.com/devlab-oy/sepa.git', :ref => 'binary-read-fix'` in the gemfile.

Now the server starts properly but there seems to be an ssql certificate issue. When running `:get_bank_certificate` command for `:danske` for example i get the following error: 

> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

So i think there is still an issue with the certificates.

**Comment by baseless** [comment]
Did some tests using your branch and seems to work ok here as well (needed to include `gem 'certified'` in gemfile). Will do a couple of more tests but looks good so far!

**Comment by baseless** [comment]
Looks fine so far, closing this issue (and await the merge :) ).
