### ISSUE TITLE
OP Certificate download not working

### ISSUE THREAD

**Issue by tjnurmin** [devlab-oy/sepa#56]
According to README, OP should work with

```
params = {
  pin: '1234567890',
  bank: :op,
  command: :get_certificate,
  customer_id: '11111111',
  environment: 'test',
  signing_csr: "...your signing.csr content..."
}
```

I am using

1. 16-digit code as pin
1. 10-digit customer id
1. using signing.csr I created (using `openssl req -out signing.csr -new -newkey rsa:2048 -nodes -keyout signing.key`)

And I only get error 26 (Technical Error) from OP. What gives?

**Comment by tjnurmin** [comment]
Should `signing.csr` be Base64'd?

**Comment by tjnurmin** [comment]
What parameters do you must give when creating the `signing.csr`? `CN =  customer id`? Anything else? You mention nothing about this in README.

**Comment by tjnurmin** [comment]
At least https://www.theseus.fi/bitstream/handle/10024/98103/Suo-Heikki_Sami.pdf?sequence=1 suggests that `Country` and `Common Name (CN)` must be given in `signing.csr`.

**Comment by ValtteriValkoinen** [comment]
This issue has nothing to do with 'sepafm' gem, it's all related to OP webservices interface. The documentation and error handling on bank's end is terrible. The error code you received "Technical error 26" seems to be the generic response given to almost all bad requests. The real reason for your error can only be found in bank's webservice logs. As an outsider developer, you can access this logging information only by calling the bank's customer support.

-
I got the correct response (signing certificate) with the following steps, so please check if you have some mistake in your process:

**1) Create the certificate signing request**
The certificate signing request must be done with the following parameters (leave all other blank):
 - C=FI
 - CN=1234567890 (this being your 10-digit customer id)

**2) Add CSR in correct format to your code**
CSR should start with -----BEGIN CERTIFICATE REQUEST----- and end with -----END CERTIFICATE REQUEST----- and line length for the hash should be 64 digits.

**3) Define environment**
I assume you are working in testing environment, so remember to define it in the call parameters. [environment: 'test']

**4) Use correct transfer keys**
Ensure you are using correct transfer keys. At least with OP there are separate key pairs for both production and test environments.

**That should do it.**

If you have already completed all the steps above without success, it's time to call the bank support and check the detailed error description from their logs. Just as a reminder, as far as I know, you must have an active webservice agreement with OP to access even the test environment. But as you have the transfer keys, this is not an issue for you.

-
There's one minor thing to correct in gem's error handling. PIN-code can and should be more than 10 characters for OP as it's formed from two 8-digit keys. The code for length verification is for 20 digits, but the error message hasn't been updated accordingly. I have left a pull request for this issue.

**Comment by tjnurmin** [comment]
@ValtteriValkoinen - thanks a lot for your kind answer. I know in my case the problem was not with the  gem itself but with the README info being rather cursory. It does not include any info on how to format the CSR.

I could make a PR on how README could be improved. This will hopefully be useful to someone else too.

And yes, I know - pretty much every bank's documentation is substandard and you always get that notorious Error Code 26. No way to know what the problem really is.

**Comment by tjnurmin** [comment]
Here's my PR:

https://github.com/devlab-oy/sepa/pull/58

**Comment by ValtteriValkoinen** [comment]
@tjnurmin - Great. Did you manage to get the certificate from OP without any problems?

**Comment by tjnurmin** [comment]
@ValtteriValkoinen - yes I did, thanks a lot!

**Comment by jonikanerva** [comment]
Thanks guys for the help! I just merged your pull request.
